import { darkenHex, lightenHex, hexLuminance } from './color.js'

// Sixteen themes: 8 dark, 8 light
// Logo filter math: white PNG base.
//   Dark themes:  invert(0.25) sepia(1) → vivid warm-cream at H≈40°, then hue-rotate to accent hue.
//   Light themes: invert(0.65) sepia(1) → medium-dark warm at H≈38°, then hue-rotate + saturate.

export const themes = {
  // ── dark ──────────────────────────────────────────────────────────────────

  charcoal: {
    label: 'charcoal',
    mode: 'dark',
    vars: {
      '--bg-base':       '#282828',
      '--bg-deep':       '#1e1e1e',
      '--bg-surface':    '#303030',
      '--bg-raised':     '#3a3a3a',
      '--bg-hover':      '#2c2c2c',
      '--border-subtle': '#404040',
      '--border-mid':    '#505050',
      '--border-strong': '#646464',
      '--text-primary':  '#f0f0f0',
      '--text-secondary':'#b0b0b0',
      '--text-muted':    '#686868',
      '--text-ghost':    '#363636',
      '--accent':        '#5cc4f8',
      '--accent-dim':    'rgba(92,196,248,0.18)',
      '--accent-faint':  'rgba(92,196,248,0.07)',
      '--accent-text':   '#0a1a28',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(170deg) saturate(2) brightness(1.15)',
    },
  },

  graphite: {
    label: 'graphite',
    mode: 'dark',
    vars: {
      '--bg-base':       '#28241e',
      '--bg-deep':       '#1e1c16',
      '--bg-surface':    '#302c26',
      '--bg-raised':     '#3a362e',
      '--bg-hover':      '#2c2820',
      '--border-subtle': '#423e36',
      '--border-mid':    '#524e44',
      '--border-strong': '#686056',
      '--text-primary':  '#ede8e0',
      '--text-secondary':'#a09080',
      '--text-muted':    '#686058',
      '--text-ghost':    '#383028',
      '--accent':        '#c87e3a',
      '--accent-dim':    'rgba(200,126,58,0.15)',
      '--accent-faint':  'rgba(200,126,58,0.06)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(346deg) saturate(2) brightness(1.05)',
    },
  },

  sunset: {
    label: 'sunset',
    mode: 'dark',
    vars: {
      '--bg-base':       '#1c1b28',
      '--bg-deep':       '#141320',
      '--bg-surface':    '#23212e',
      '--bg-raised':     '#2c2a3c',
      '--bg-hover':      '#1f1d2a',
      '--border-subtle': '#2e2c42',
      '--border-mid':    '#3c3a54',
      '--border-strong': '#504e6c',
      '--text-primary':  '#eadcc8',
      '--text-secondary':'#8a8090',
      '--text-muted':    '#504858',
      '--text-ghost':    '#2a2830',
      '--accent':        '#e87a3a',
      '--accent-dim':    'rgba(232,122,58,0.15)',
      '--accent-faint':  'rgba(232,122,58,0.06)',
      '--accent-text':   '#1c1b28',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(345deg) saturate(2.5) brightness(1.1)',
    },
  },

  retro: {
    label: 'retro',
    mode: 'dark',
    vars: {
      '--bg-base':       '#0e1a30',
      '--bg-deep':       '#081220',
      '--bg-surface':    '#142238',
      '--bg-raised':     '#1a2c48',
      '--bg-hover':      '#101e34',
      '--border-subtle': '#1c3050',
      '--border-mid':    '#284060',
      '--border-strong': '#345278',
      '--text-primary':  '#c8e0f4',
      '--text-secondary':'#6090c0',
      '--text-muted':    '#304860',
      '--text-ghost':    '#142030',
      '--accent':        '#e040c0',
      '--accent-dim':    'rgba(224,64,192,0.15)',
      '--accent-faint':  'rgba(224,64,192,0.07)',
      '--accent-text':   '#0e1a30',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(266deg) saturate(2.5) brightness(1.2)',
    },
  },

  midnight: {
    label: 'midnight',
    mode: 'dark',
    vars: {
      '--bg-base':       '#1a1b26',
      '--bg-deep':       '#13141e',
      '--bg-surface':    '#1f2035',
      '--bg-raised':     '#282a3e',
      '--bg-hover':      '#1d1f32',
      '--border-subtle': '#292b42',
      '--border-mid':    '#363858',
      '--border-strong': '#4c4f70',
      '--text-primary':  '#c0caf5',
      '--text-secondary':'#6d7ec4',
      '--text-muted':    '#3c4270',
      '--text-ghost':    '#21243a',
      '--accent':        '#7aa2f7',
      '--accent-dim':    'rgba(122,162,247,0.15)',
      '--accent-faint':  'rgba(122,162,247,0.06)',
      '--accent-text':   '#1a1b26',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(181deg) saturate(2) brightness(1.15)',
    },
  },

  slate: {
    label: 'slate',
    mode: 'dark',
    vars: {
      '--bg-base':       '#1e2430',
      '--bg-deep':       '#161c26',
      '--bg-surface':    '#242c38',
      '--bg-raised':     '#2c3444',
      '--bg-hover':      '#222a36',
      '--border-subtle': '#2e3848',
      '--border-mid':    '#3c4858',
      '--border-strong': '#506070',
      '--text-primary':  '#c8d8e8',
      '--text-secondary':'#6e8ca8',
      '--text-muted':    '#445a70',
      '--text-ghost':    '#202e3c',
      '--accent':        '#3cbeb0',
      '--accent-dim':    'rgba(60,190,176,0.15)',
      '--accent-faint':  'rgba(60,190,176,0.06)',
      '--accent-text':   '#1e2430',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(135deg) saturate(2) brightness(1.1)',
    },
  },

  moss: {
    label: 'moss',
    mode: 'dark',
    vars: {
      '--bg-base':       '#181f16',
      '--bg-deep':       '#111710',
      '--bg-surface':    '#1e2619',
      '--bg-raised':     '#252e20',
      '--bg-hover':      '#1c2318',
      '--border-subtle': '#283222',
      '--border-mid':    '#34402c',
      '--border-strong': '#485840',
      '--text-primary':  '#c8d8b0',
      '--text-secondary':'#6c8c58',
      '--text-muted':    '#485c38',
      '--text-ghost':    '#222c1c',
      '--accent':        '#84c44a',
      '--accent-dim':    'rgba(132,196,74,0.14)',
      '--accent-faint':  'rgba(132,196,74,0.06)',
      '--accent-text':   '#181f16',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(50deg) saturate(2) brightness(1.1)',
    },
  },

  ember: {
    label: 'ember',
    mode: 'dark',
    vars: {
      '--bg-base':       '#1c1412',
      '--bg-deep':       '#130e0c',
      '--bg-surface':    '#221a16',
      '--bg-raised':     '#2c201c',
      '--bg-hover':      '#201614',
      '--border-subtle': '#2e1e1a',
      '--border-mid':    '#3e2c26',
      '--border-strong': '#543c36',
      '--text-primary':  '#f0d4b8',
      '--text-secondary':'#a07860',
      '--text-muted':    '#644840',
      '--text-ghost':    '#2e1e1a',
      '--accent':        '#e83838',
      '--accent-dim':    'rgba(232,56,56,0.15)',
      '--accent-faint':  'rgba(232,56,56,0.06)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(320deg) saturate(2.5) brightness(1.1)',
    },
  },

  // ── light ─────────────────────────────────────────────────────────────────

  paper: {
    label: 'paper',
    mode: 'light',
    vars: {
      '--bg-base':       '#f5f5f0',
      '--bg-deep':       '#ebebea',
      '--bg-surface':    '#fafaf8',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#f0f0ec',
      '--border-subtle': '#e0e0db',
      '--border-mid':    '#d0d0ca',
      '--border-strong': '#b0b0aa',
      '--text-primary':  '#1a1a18',
      '--text-secondary':'#525250',
      '--text-muted':    '#909090',
      '--text-ghost':    '#d4d4d0',
      '--accent':        '#c8201a',
      '--accent-dim':    'rgba(200,32,26,0.12)',
      '--accent-faint':  'rgba(200,32,26,0.05)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(324deg) saturate(4) brightness(0.85)',
    },
  },

  latte: {
    label: 'latte',
    mode: 'light',
    vars: {
      '--bg-base':       '#f5f0e8',
      '--bg-deep':       '#ede8de',
      '--bg-surface':    '#faf7f2',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#ede8e0',
      '--border-subtle': '#e4ddd0',
      '--border-mid':    '#d0c8b8',
      '--border-strong': '#b8a890',
      '--text-primary':  '#2a2418',
      '--text-secondary':'#6a5e50',
      '--text-muted':    '#9a8e80',
      '--text-ghost':    '#d4cec4',
      '--accent':        '#c8601a',
      '--accent-dim':    'rgba(200,96,26,0.12)',
      '--accent-faint':  'rgba(200,96,26,0.05)',
      '--accent-text':   '#faf7f2',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(348deg) saturate(3.5) brightness(0.82)',
    },
  },

  flashbang: {
    label: 'flashbang',
    mode: 'light',
    vars: {
      '--bg-base':       '#f8f8f6',
      '--bg-deep':       '#f0f0ee',
      '--bg-surface':    '#ffffff',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#f2f2f0',
      '--border-subtle': '#e8e8e4',
      '--border-mid':    '#d4d4d0',
      '--border-strong': '#b8b8b4',
      '--text-primary':  '#141414',
      '--text-secondary':'#484848',
      '--text-muted':    '#909090',
      '--text-ghost':    '#d0d0d0',
      '--accent':        '#e8c000',
      '--accent-dim':    'rgba(232,192,0,0.18)',
      '--accent-faint':  'rgba(232,192,0,0.07)',
      '--accent-text':   '#141414',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(12deg) saturate(4) brightness(0.72)',
    },
  },

  girlypop: {
    label: 'girlypop',
    mode: 'light',
    vars: {
      '--bg-base':       '#fce8f0',
      '--bg-deep':       '#f5dce8',
      '--bg-surface':    '#fef4f8',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#f5e5f0',
      '--border-subtle': '#eac8d8',
      '--border-mid':    '#d8b0c4',
      '--border-strong': '#c090b0',
      '--text-primary':  '#3c1828',
      '--text-secondary':'#7a4860',
      '--text-muted':    '#b07898',
      '--text-ghost':    '#e8c8d8',
      '--accent':        '#5aace8',
      '--accent-dim':    'rgba(90,172,232,0.18)',
      '--accent-faint':  'rgba(90,172,232,0.07)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(168deg) saturate(4) brightness(0.82)',
    },
  },

  cream: {
    label: 'cream',
    mode: 'light',
    vars: {
      '--bg-base':       '#f4f0e2',
      '--bg-deep':       '#e8e4d2',
      '--bg-surface':    '#faf8ee',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#ece8d8',
      '--border-subtle': '#e0d8c0',
      '--border-mid':    '#ccc0a4',
      '--border-strong': '#b0a080',
      '--text-primary':  '#281e0a',
      '--text-secondary':'#6c5c38',
      '--text-muted':    '#9a8a60',
      '--text-ghost':    '#d8d0b4',
      '--accent':        '#d4a418',
      '--accent-dim':    'rgba(212,164,24,0.18)',
      '--accent-faint':  'rgba(212,164,24,0.07)',
      '--accent-text':   '#281e0a',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(7deg) saturate(3.5) brightness(0.7)',
    },
  },

  dusk: {
    label: 'dusk',
    mode: 'light',
    vars: {
      '--bg-base':       '#f0eef8',
      '--bg-deep':       '#e6e2f2',
      '--bg-surface':    '#f8f6ff',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#e8e4f4',
      '--border-subtle': '#dcd6f0',
      '--border-mid':    '#c8bee4',
      '--border-strong': '#a898d0',
      '--text-primary':  '#26204c',
      '--text-secondary':'#685aa8',
      '--text-muted':    '#9880cc',
      '--text-ghost':    '#dcd6f0',
      '--accent':        '#8c3ed0',
      '--accent-dim':    'rgba(140,62,208,0.13)',
      '--accent-faint':  'rgba(140,62,208,0.05)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(238deg) saturate(5) brightness(0.78)',
    },
  },

  peach: {
    label: 'peach',
    mode: 'light',
    vars: {
      '--bg-base':       '#fdf0e4',
      '--bg-deep':       '#f5e4d0',
      '--bg-surface':    '#fff8f2',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#f4e4d0',
      '--border-subtle': '#eed4ba',
      '--border-mid':    '#d8bca0',
      '--border-strong': '#be9c80',
      '--text-primary':  '#3a1c10',
      '--text-secondary':'#8a5840',
      '--text-muted':    '#b48a70',
      '--text-ghost':    '#ead4bc',
      '--accent':        '#c83c5c',
      '--accent-dim':    'rgba(200,60,92,0.14)',
      '--accent-faint':  'rgba(200,60,92,0.05)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(310deg) saturate(5) brightness(0.8)',
    },
  },

  mint: {
    label: 'mint',
    mode: 'light',
    vars: {
      '--bg-base':       '#edf8f1',
      '--bg-deep':       '#e0f0e6',
      '--bg-surface':    '#f4fbf7',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#e4f2e9',
      '--border-subtle': '#cce8d6',
      '--border-mid':    '#b4d8c0',
      '--border-strong': '#8cc0a8',
      '--text-primary':  '#0e2c1e',
      '--text-secondary':'#3a6e50',
      '--text-muted':    '#6ea080',
      '--text-ghost':    '#c0e0d0',
      '--accent':        '#1a9c60',
      '--accent-dim':    'rgba(26,156,96,0.14)',
      '--accent-faint':  'rgba(26,156,96,0.06)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(117deg) saturate(5) brightness(0.78)',
    },
  },

  // ── extra (wild) ───────────────────────────────────────────────────────────

  neon: {
    label: 'neon',
    mode: 'dark',
    vars: {
      '--bg-base':       '#06060e',
      '--bg-deep':       '#03030a',
      '--bg-surface':    '#0c0c18',
      '--bg-raised':     '#121228',
      '--bg-hover':      '#090916',
      '--border-subtle': '#14143a',
      '--border-mid':    '#202050',
      '--border-strong': '#303070',
      '--text-primary':  '#d8f0ff',
      '--text-secondary':'#5070c0',
      '--text-muted':    '#2a3870',
      '--text-ghost':    '#101830',
      '--accent':        '#00ffcc',
      '--accent-dim':    'rgba(0,255,204,0.12)',
      '--accent-faint':  'rgba(0,255,204,0.05)',
      '--accent-text':   '#000e0a',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(128deg) saturate(6) brightness(1.5)',
    },
  },

  acid: {
    label: 'acid',
    mode: 'dark',
    vars: {
      '--bg-base':       '#0a0c06',
      '--bg-deep':       '#060804',
      '--bg-surface':    '#10120a',
      '--bg-raised':     '#181c10',
      '--bg-hover':      '#0e1008',
      '--border-subtle': '#1c2010',
      '--border-mid':    '#282e18',
      '--border-strong': '#383e24',
      '--text-primary':  '#e4f0b0',
      '--text-secondary':'#7a9040',
      '--text-muted':    '#485a28',
      '--text-ghost':    '#1e2410',
      '--accent':        '#ccff00',
      '--accent-dim':    'rgba(204,255,0,0.11)',
      '--accent-faint':  'rgba(204,255,0,0.04)',
      '--accent-text':   '#090c02',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(40deg) saturate(7) brightness(1.7)',
    },
  },

  aurora: {
    label: 'aurora',
    mode: 'dark',
    vars: {
      '--bg-base':       '#080e1a',
      '--bg-deep':       '#040914',
      '--bg-surface':    '#0c1422',
      '--bg-raised':     '#101c2e',
      '--bg-hover':      '#0a1220',
      '--border-subtle': '#121e34',
      '--border-mid':    '#1c2e4e',
      '--border-strong': '#284068',
      '--text-primary':  '#c4e4ff',
      '--text-secondary':'#4878b8',
      '--text-muted':    '#243e68',
      '--text-ghost':    '#0e1c30',
      '--accent':        '#ff40c0',
      '--accent-dim':    'rgba(255,64,192,0.13)',
      '--accent-faint':  'rgba(255,64,192,0.05)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(270deg) saturate(4) brightness(1.35)',
    },
  },

  void: {
    label: 'void',
    mode: 'dark',
    vars: {
      '--bg-base':       '#0c0614',
      '--bg-deep':       '#08040e',
      '--bg-surface':    '#12091e',
      '--bg-raised':     '#1a0e2c',
      '--bg-hover':      '#100818',
      '--border-subtle': '#1c1030',
      '--border-mid':    '#2c1a48',
      '--border-strong': '#3e2860',
      '--text-primary':  '#ead8ff',
      '--text-secondary':'#8050c8',
      '--text-muted':    '#402070',
      '--text-ghost':    '#1a1030',
      '--accent':        '#bf00ff',
      '--accent-dim':    'rgba(191,0,255,0.13)',
      '--accent-faint':  'rgba(191,0,255,0.05)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(246deg) saturate(5) brightness(1.3)',
    },
  },

  terminal: {
    label: 'terminal',
    mode: 'dark',
    vars: {
      '--bg-base':       '#040c04',
      '--bg-deep':       '#020802',
      '--bg-surface':    '#071007',
      '--bg-raised':     '#0c180c',
      '--bg-hover':      '#060e06',
      '--border-subtle': '#0e1e0e',
      '--border-mid':    '#162a16',
      '--border-strong': '#1e3a1e',
      '--text-primary':  '#00ff44',
      '--text-secondary':'#00b830',
      '--text-muted':    '#006618',
      '--text-ghost':    '#001c08',
      '--accent':        '#00ff44',
      '--accent-dim':    'rgba(0,255,68,0.12)',
      '--accent-faint':  'rgba(0,255,68,0.04)',
      '--accent-text':   '#020802',
      '--logo-filter':   'invert(0.25) sepia(1) hue-rotate(76deg) saturate(8) brightness(1.6)',
    },
  },

  vapor: {
    label: 'vapor',
    mode: 'light',
    vars: {
      '--bg-base':       '#f0dff8',
      '--bg-deep':       '#e4d0ec',
      '--bg-surface':    '#faf4ff',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#ead5f4',
      '--border-subtle': '#dfc8f0',
      '--border-mid':    '#c8a8e0',
      '--border-strong': '#a880cc',
      '--text-primary':  '#1a0830',
      '--text-secondary':'#6a30a8',
      '--text-muted':    '#a068c8',
      '--text-ghost':    '#e8d4f8',
      '--accent':        '#00c8e8',
      '--accent-dim':    'rgba(0,200,232,0.18)',
      '--accent-faint':  'rgba(0,200,232,0.07)',
      '--accent-text':   '#020e14',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(155deg) saturate(6) brightness(0.75)',
    },
  },

  cobalt: {
    label: 'cobalt',
    mode: 'light',
    vars: {
      '--bg-base':       '#ddeeff',
      '--bg-deep':       '#cce0f8',
      '--bg-surface':    '#eef6ff',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#d4e8ff',
      '--border-subtle': '#c4d8f4',
      '--border-mid':    '#a4c0e8',
      '--border-strong': '#7ca4d8',
      '--text-primary':  '#06203c',
      '--text-secondary':'#2a5888',
      '--text-muted':    '#5888c0',
      '--text-ghost':    '#bcd4f0',
      '--accent':        '#ff5f00',
      '--accent-dim':    'rgba(255,95,0,0.16)',
      '--accent-faint':  'rgba(255,95,0,0.06)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(340deg) saturate(6) brightness(0.75)',
    },
  },

  candy: {
    label: 'candy',
    mode: 'light',
    vars: {
      '--bg-base':       '#ddf8f2',
      '--bg-deep':       '#cceeea',
      '--bg-surface':    '#edfdf8',
      '--bg-raised':     '#ffffff',
      '--bg-hover':      '#d4f4ee',
      '--border-subtle': '#beeae2',
      '--border-mid':    '#9ed4cc',
      '--border-strong': '#6cbaB0',
      '--text-primary':  '#062820',
      '--text-secondary':'#286858',
      '--text-muted':    '#509888',
      '--text-ghost':    '#bce8e0',
      '--accent':        '#ff1a70',
      '--accent-dim':    'rgba(255,26,112,0.16)',
      '--accent-faint':  'rgba(255,26,112,0.06)',
      '--accent-text':   '#ffffff',
      '--logo-filter':   'invert(0.65) sepia(1) hue-rotate(300deg) saturate(6) brightness(0.76)',
    },
  },
}

export const DEFAULT_THEME = 'charcoal'

export const DEFAULT_CUSTOM_COLORS = { bg: '#282828', accent: '#5cc4f8', text: '#f0f0f0' }

function blend(from, to, t) {
  const f = (h, o) => parseInt(h.slice(o, o + 2), 16)
  const lerp = (a, b) => Math.round(a + (b - a) * t)
  const r = lerp(f(from, 1), f(to, 1))
  const g = lerp(f(from, 3), f(to, 3))
  const b = lerp(f(from, 5), f(to, 5))
  return `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`
}

export function generateCustomTheme(bg, accent, text) {
  const isDark = hexLuminance(bg) < 0.45

  const bgDeep     = isDark ? darkenHex(bg, 0.20)  : darkenHex(bg, 0.06)
  const bgSurface  = isDark ? lightenHex(bg, 0.10)  : lightenHex(bg, 0.03)
  const bgRaised   = isDark ? lightenHex(bg, 0.22)  : lightenHex(bg, 0.07)
  const bgHover    = isDark ? lightenHex(bg, 0.06)  : darkenHex(bg, 0.04)
  const bordSubtle = isDark ? lightenHex(bg, 0.16)  : darkenHex(bg, 0.10)
  const bordMid    = isDark ? lightenHex(bg, 0.28)  : darkenHex(bg, 0.20)
  const bordStrong = isDark ? lightenHex(bg, 0.45)  : darkenHex(bg, 0.35)
  const textSec    = blend(text, bg, isDark ? 0.42 : 0.38)
  const textMuted  = blend(text, bg, isDark ? 0.65 : 0.60)
  const textGhost  = blend(text, bg, isDark ? 0.82 : 0.78)

  const ar = parseInt(accent.slice(1, 3), 16)
  const ag = parseInt(accent.slice(3, 5), 16)
  const ab = parseInt(accent.slice(5, 7), 16)

  return {
    '--bg-base':       bg,
    '--bg-deep':       bgDeep,
    '--bg-surface':    bgSurface,
    '--bg-raised':     bgRaised,
    '--bg-hover':      bgHover,
    '--border-subtle': bordSubtle,
    '--border-mid':    bordMid,
    '--border-strong': bordStrong,
    '--text-primary':  text,
    '--text-secondary':textSec,
    '--text-muted':    textMuted,
    '--text-ghost':    textGhost,
    '--accent':        accent,
    '--accent-dim':    `rgba(${ar},${ag},${ab},0.15)`,
    '--accent-faint':  `rgba(${ar},${ag},${ab},0.07)`,
    '--accent-text':   hexLuminance(accent) > 0.45 ? '#111111' : '#f8f8f8',
    '--logo-filter':   isDark
      ? 'invert(0.25) sepia(1) brightness(1.1)'
      : 'invert(0.65) sepia(1) brightness(0.8)',
  }
}
